version: '3'

services:
  rabbitmq1:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      NAME: "rabbitmq1"
    networks:
      - rabbitmq_cluster

  rabbitmq2:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq2"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5673:5672"
      - "15673:15672"
    labels:
      NAME: "rabbitmq2"
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq_cluster

  rabbitmq3:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq3"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5674:5672"
      - "15674:15672"
    labels:
      NAME: "rabbitmq3"
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq_cluster

networks:
  rabbitmq_cluster:
    driver: bridge
